% [ t, x, u, p ] = trans( trjs )
%
% Concatenate just the event data constructed from trajectories
%
% Inputs:
% trjs - struct - trajectories generated by fwd_euler
%
% Outputs:
% t - 1 x  Nt - discretization times
% x - Nt x Nx - state at discretization times
% u - Nt x Nu - input at discretization times
% p - Nt x Np - parameters at discretization times
%
% by Sam Burden, Humberto Gonzalez, Ram Vasudevan, 2013

function [ t, x, u, p ] = trans( trjs )

% constructing arrays that we fill in
t = []; x = []; u = []; p = [];

for k = 1:( length( trjs ) - 1 )
    if length( trjs( k ).t ) > 2
        t = [ t; trjs( k ).t( [ 1, end - 1, end ] )' ];
        x = [ x; trjs( k ).x( [ 1, end - 1, end ], : )  ];
        u = [ u; trjs( k ).u( [ 1, end - 1, end ], : ) ];
        p = [ p; trjs( k ).p ];
    end
end

end


